
; print debug output

print ""
if !FEATURE_PAL
print "NTSC / [PAL] REGION"
else
print "[NTSC] / PAL REGION"
endif

if !FEATURE_SD2SNES
print "SAVESTATES ENABLED"
incsrc save.asm
else
print "SAVESTATES DISABLED"
endif

if !FEATURE_TINYSTATES
print "TINYSTATES ENABLED"
incsrc tinystates.asm
; Set to enable savestate features
!FEATURE_SD2SNES = 1
endif

if !FEATURE_TINYSTATES
print "SAVESTATES / [TINYSTATES] / NO SAVES"
elseif !FEATURE_SAVESTATES
print "[SAVESTATES] / TINYSTATES / NO SAVES"
else
print "SAVESTATES / TINYSTATES / [NO SAVES]"
endif

if !FEATURE_VANILLAHUD
print " INFOHUD / [VANILLA HUD]"
else
print " [INFOHUD] / VANILLA HUD"
endif

if !FEATURE_EXTRAS
print "EXTRAS FEATURES ENABLED"
endif

if !ORIGINAL_MESSAGE_TEXT
print "PRESERVE FANFARE MESSAGES"
endif

if !RAW_TILE_GRAPHICS
else
print "FAST PRESETS DISABLED"
endif

if !PRESERVE_WRAM_DURING_SPACETIME == 0
print "SPACETIME PROTECTION DISABLED"
endif

if !FEATURE_DEV
print "DEVELOPER MODE ENABLED"
endif
